# CC = gcc
# LD = gcc

# OBJ = main.o

# main : $(OBJ)
# 	@$(LD) $(OBJ) -o main
# 	# ./main
# 	@rm -f *.o

# main.o : main.c main.h

# .c.o : 
# 	@$(CC) -c $< -o $@

# clean : 
# 	rm -f *.o main

build : 
	@gcc -pthread main.c -o main